# Generated by Django 5.1 on 2024-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GENERAL', 'General OPD'), ('SPECIALTY', 'Specialty OPD'), ('EMERGENCY', 'Emergency OPD'), ('CARDIOLOGY', 'Cardiology OPD'), ('NEUROLOGY', 'Neurology OPD'), ('ONCOLOGY', 'Oncology OPD'), ('GYNAECOLOGY', 'Gynaecology OPD')], max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opd',
                'verbose_name_plural': 'Opds',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
