# Generated by Django 5.1 on 2024-09-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_type', models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('GW', 'General Ward'), ('A&E', 'Accident and Emergency Ward'), ('CCU', 'Cardiac Care Unit'), ('PICU', 'Pediatric Intensive Care Unit'), ('NICU', 'Neonatal Intensive Care Unit'), ('HDU', 'High Dependency Unit'), ('MSW', 'Medical and Surgical Ward'), ('ONCOLOGY', 'Oncology')], max_length=255)),
                ('capacity', models.IntegerField()),
                ('occupied', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital.hospital')),
            ],
            options={
                'verbose_name_plural': 'Beds',
                'ordering': ['-created_at'],
            },
        ),
    ]
