# Generated by Django 5.1.1 on 2024-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='opd',
        ),
    ]
