# Generated by Django 5.1.1 on 2024-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_bed_remove_hospital_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Semi-Government', 'Semi-Government'), ('Healthcentere', 'Healthcentere')], default='Government', max_length=50),
        ),
    ]
